### ISSUE TITLE
SymHighlightV2/HighlightDialog.e issue in latest SE 22.0.2

### ISSUE THREAD

**Issue by DaPa** [jporkka/slickMacros#1]
SlickEdit Pro 2017 (v22.0.2.1 64-bit) on Win7x64, in SymHighlightV2/HighlightDialog.e:
I had to replace s_list_ctrl._TreeGetNextIndex(**0**) with s_list_ctrl._TreeGetNextIndex(**TREE_ROOT_INDEX**) else I was getting a "This property or method is not allowed on this object" there:

`
static int findItem(int s_list_ctrl, _str key)
{
    int found = -1;
    int index = s_list_ctrl._TreeGetNextIndex(0); // <= here: had to replace 0 with TREE_ROOT_INDEX
    while (index != -1)
    {
        _str text =  s_list_ctrl._TreeGetCaption(index, FC_NEEDLE);
        if (text == key)
        {
            found = index;
            break;
        }
        index = s_list_ctrl._TreeGetNextIndex(index);
    }
    return found;
}
`

**Comment by jporkka** [comment]
That shouldn't make a difference, as it is the same:
const TREE_ROOT_INDEX=     0;

Do you have repro steps?
Does it repro if you put it back to 0?

**Comment by DaPa** [comment]
Sorry for late answer. I put back to 0 and still works, so probably was some issue when installed 22.0.2.
Please close the issue as I have no problems anymore. Thanks for this nice macro!
